# Generated by Django 5.0.4 on 2024-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
