# Generated by Django 5.0.4 on 2024-05-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_semestre_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
