# Generated by Django 4.2.6 on 2024-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expirandotoken_autoavaliacao_idturma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoavaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
